# Generated by Django 5.0.1 on 2024-01-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='money_earned',
            new_name='money_earned_DO_NOT_MODIFY',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pieces_sold',
            new_name='pieces_sold_DO_NOT_MODIFY',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='ecommerce/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
            ],
        ),
    ]
