# Generated by Django 5.0.1 on 2024-01-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_rename_productimages_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='Category name', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=models.CharField(default='Longer description to appear on the product page. If you dont want any info here just leave it blank.', max_length=600),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default='Short description to appear on the home page and next to the product.', max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(default='Subcategory name', max_length=50),
        ),
    ]
