# Generated by Django 5.0.1 on 2024-01-30 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_product_product_name_alter_product_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 30, 22, 57, 26, 537079, tzinfo=datetime.timezone.utc)),
        ),
    ]
