# Generated by Django 5.0.1 on 2024-01-31 13:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_alter_product_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 13, 1, 16, 491938, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
