# Generated by Django 5.0.1 on 2024-01-31 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_remove_productinorder_price_alter_product_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_session',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 13, 42, 5, 379801, tzinfo=datetime.timezone.utc)),
        ),
    ]
