# Generated by Django 5.0.1 on 2024-01-31 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_order_order_session_alter_product_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 13, 44, 28, 292482, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
