# Generated by Django 5.0.1 on 2024-01-31 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_product_pub_date_alter_productinorder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('site_name', models.CharField(default='Ecommerce site', max_length=100)),
                ('site_logo', models.ImageField(default='', upload_to='ecommerce/images')),
                ('site_favicon', models.ImageField(default='', upload_to='ecommerce/images')),
                ('site_description', models.CharField(default='Ecommerce site', max_length=100)),
                ('facebook_link', models.CharField(default='https://www.facebook.com/', max_length=100)),
                ('twitter_link', models.CharField(default='https://twitter.com/', max_length=100)),
                ('instagram_link', models.CharField(default='https://www.instagram.com/', max_length=100)),
                ('youtube_link', models.CharField(default='https://www.youtube.com/', max_length=100)),
                ('email', models.CharField(default='user@gmail.com', max_length=100)),
                ('phone', models.CharField(default='1234567890', max_length=100)),
                ('address', models.CharField(default='1234 Main St', max_length=100)),
                ('address2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='Anytown', max_length=100)),
                ('state', models.CharField(default='NY', max_length=100)),
                ('zip_code', models.CharField(default='12345', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=100)),
                ('currency_symbol', models.CharField(default='$', max_length=100)),
                ('stripe_api', models.CharField(default='GO ON THE WEBSITE AND GET YOUR OWN API KEY', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 14, 36, 50, 922121, tzinfo=datetime.timezone.utc)),
        ),
    ]
