# Generated by Django 5.0.1 on 2024-02-01 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_settings_alter_product_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='stripe_api',
            new_name='STRIPE_LIVE_PUBLIC_KEY',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='settings',
            name='STRIPE_LIVE_SECRET_KEY',
            field=models.CharField(default='GO ON THE WEBSITE AND GET YOUR OWN API KEY', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='STRIPE_TEST_PUBLIC_KEY',
            field=models.CharField(default='GO ON THE WEBSITE AND GET YOUR OWN API KEY', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='STRIPE_TEST_SECRET_KEY',
            field=models.CharField(default='GO ON THE WEBSITE AND GET YOUR OWN API KEY', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='test_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='TrackingNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(default='', max_length=50)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
            ],
        ),
    ]
