# Generated by Django 5.0.1 on 2024-02-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_rename_stripe_api_settings_stripe_live_public_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='STRIPE_LIVE_PUBLIC_KEY',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='STRIPE_LIVE_SECRET_KEY',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='STRIPE_TEST_PUBLIC_KEY',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='STRIPE_TEST_SECRET_KEY',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='city',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='state',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='zip_code',
        ),
    ]
