# Generated by Django 5.0.1 on 2024-02-04 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_remove_settings_facebook_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(default='Call to action', max_length=100)),
                ('link', models.CharField(default='https://www.facebook.com/', max_length=100)),
                ('putInHeader', models.BooleanField(default=False)),
                ('putInFooter', models.BooleanField(default=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.settings')),
            ],
        ),
    ]
