# Generated by Django 5.0.1 on 2024-02-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_calltoaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='fontAwesomeIcon',
            field=models.CharField(default='fas fa-shopping-cart', max_length=100),
        ),
    ]
