# Generated by Django 5.0.1 on 2024-02-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_rename_fontawesomeicon_calltoaction_fontawesomeiconclassname'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='column_size_big_screen',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='settings',
            name='column_size_margin',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='settings',
            name='column_size_short_screen',
            field=models.IntegerField(default=6),
        ),
    ]
