# Generated by Django 5.0.1 on 2024-02-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0035_alter_settings_column_size_big_screen_carouselimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='ecommerce/images'),
        ),
    ]
