# Generated by Django 5.0.1 on 2024-02-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_settings_buy_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='main_color',
            field=models.CharField(default='#007bff', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=100),
        ),
    ]
