# Generated by Django 5.0.1 on 2024-02-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_settings_main_color_settings_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='navbar_color',
            field=models.CharField(default='#FFFFFF', max_length=100),
        ),
    ]
