# Generated by Django 5.0.1 on 2024-02-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_alter_settings_main_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='product_best_seller_text',
            field=models.CharField(default='Best seller', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='product_featured_text',
            field=models.CharField(default='Featured', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='product_last_chance_number',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='product_last_chance_text',
            field=models.CharField(default='Last chance', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='product_new_text',
            field=models.CharField(default='New', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='product_out_of_stock_text',
            field=models.CharField(default='Out of stock', max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='secondary_color',
            field=models.CharField(default='3b71ca', max_length=100),
        ),
        migrations.CreateModel(
            name='FrontPageProductShowcase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Title', max_length=100)),
                ('subtitle', models.CharField(default='Subtitle', max_length=100)),
                ('description', models.CharField(default='Description', max_length=100)),
                ('new_products', models.BooleanField(default=False)),
                ('best_sellers', models.BooleanField(default=False)),
                ('featured_products', models.BooleanField(default=False)),
                ('last_bought', models.BooleanField(default=False)),
                ('last_seen', models.BooleanField(default=False)),
                ('last_chance', models.BooleanField(default=False)),
                ('promotion', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category')),
                ('products', models.ManyToManyField(to='ecommerce.product')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.settings')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.subcategory')),
            ],
        ),
    ]
