# Generated by Django 5.0.1 on 2024-02-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0042_settings_product_best_seller_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='checkout_delete_button_text',
            field=models.CharField(default='Delete', max_length=100),
        ),
    ]
