# Generated by Django 5.0.1 on 2024-02-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0045_rename_textlanguages_settings_textlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='textLanguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.textlanguage'),
        ),
    ]
