# Generated by Django 5.0.1 on 2024-02-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0046_alter_settings_textlanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='textLanguage',
        ),
    ]
