# Generated by Django 5.0.1 on 2024-02-10 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0047_remove_settings_textlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='selectedTextLanguage',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.textlanguage'),
        ),
    ]
