# Generated by Django 5.0.1 on 2024-02-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0048_settings_selectedtextlanguage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='selectedTextLanguage',
            new_name='textLanguage',
        ),
    ]
