# Generated by Django 5.0.1 on 2024-02-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0049_rename_selectedtextlanguage_settings_textlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='number_of_best_sellers',
            field=models.IntegerField(default=5),
        ),
    ]
