# Generated by Django 5.0.1 on 2024-02-10 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0050_settings_number_of_best_sellers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pieces_sold_DO_NOT_MODIFY',
            new_name='items_sold_DO_NOT_MODIFY',
        ),
    ]
