# Generated by Django 5.0.1 on 2024-02-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0051_rename_pieces_sold_do_not_modify_product_items_sold_do_not_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
